import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
test('native launcher handles spaced paths, forwards args and uses original runtime on corrupt adapter', {timeout:120000}, () => {
  const root=mkdtempSync(join(tmpdir(),'jev launcher '));mkdirSync(join(root,'runtime/desktop'),{recursive:true});mkdirSync(join(root,'scripts'));
  const binary=join(root,process.platform==='win32'?'jev-pilot.exe':'jev-pilot');
  execFileSync('go',['build','-o',binary,fileURLToPath(new URL('../launcher/main.go',import.meta.url))],{timeout:100000});
  const configPath=join(root,'runtime/desktop/install.json');
  const config={node:process.execPath,realBin:process.execPath,sha256:{}};
  writeFileSync(configPath,JSON.stringify(config));
  writeFileSync(join(root,'runtime/desktop/bootstrap.mjs'),'console.log(JSON.stringify({args:process.argv.slice(2),keyPresent:Boolean(process.env.TYPESAFE_API_KEY)}))');
  writeFileSync(join(root,'scripts/cli.mjs'),'console.log(JSON.stringify({cli:process.argv[2]}))');
  const env={...process.env,TYPESAFE_API_KEY:'test-fixture',CODEX_CLI_PATH:binary};
  const normal=JSON.parse(execFileSync(binary,['app-server','with space',"quote'\""],{env,encoding:'utf8'}));
  assert.deepEqual(normal.args,['app-server','with space',"quote'\""]);assert.equal(normal.keyPresent,true);
  writeFileSync(configPath,JSON.stringify({...config,sha256:{'missing.mjs':'bad'}}));
  const fallback=JSON.parse(execFileSync(binary,['-e','console.log(JSON.stringify({native:true,keyPresent:Boolean(process.env.TYPESAFE_API_KEY),recursive:Boolean(process.env.CODEX_CLI_PATH)}))'],{env,encoding:'utf8'}));
  assert.equal(fallback.native,true);assert.equal(fallback.keyPresent,false);assert.equal(fallback.recursive,false);
  assert.equal(JSON.parse(execFileSync(binary,['doctor'],{env,encoding:'utf8'})).cli,'doctor');
  writeFileSync(configPath,JSON.stringify({...config,node:join(root,'removed-node'),sha256:{}}));
  const missingNode=JSON.parse(execFileSync(binary,['-e','console.log(JSON.stringify({native:true,keyPresent:Boolean(process.env.TYPESAFE_API_KEY)}))'],{env,encoding:'utf8'}));
  assert.equal(missingNode.native,true);assert.equal(missingNode.keyPresent,false);
});
