import test from 'node:test';import assert from 'node:assert/strict';import{Router,effortQuestion,horizonQuestion}from'../runtime/desktop/router.mjs';
const choice=(q,c)=>({type:'choice',choice:c,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===c?1:0]))});
function fixture(){let calls=0,time=100000,selected='medium',fail=false;const logs=[],updates=[];const r=new Router({coalesceMs:0,clock:()=>time,judge:async()=>{calls++;if(fail)throw Error('JEV_TIMEOUT');return{answer:choice(effortQuestion,selected),horizon:choice(horizonQuestion,'1')};},request:async(m,p)=>{updates.push(p);return{status:'applied'};},log:x=>logs.push(x)});r.supported.set('gpt-6-sol',['low','medium','high']);return{r,logs,updates,get calls(){return calls;},advance:ms=>time+=ms,select:x=>selected=x,fail:x=>fail=x};}
async function start(f,text='Investigate a task'){const p={threadId:'t',model:'gpt-6-sol',effort:'medium',cwd:'/p',input:[{type:'text',text}]},t=f.r.start('t',p);t.turnId='turn'+f.calls;await f.r.routeStart(p,t);return t;}
const hook=(f,id,response='observed result')=>{const t=f.r.turns.get('t');return f.r.hook({session_id:'t',turn_id:t.turnId,hook_event_name:'PostToolUse',tool_use_id:id,tool_name:'exec',tool_response:response});};
function complete(f){const t=f.r.turns.get('t');f.r.observe({method:'turn/completed',params:{threadId:'t',turn:{id:t.turnId,status:'completed'}}});}
test('a new task remains eligible after two completed no-change turns',async()=>{const f=fixture();for(let n=0;n<2;n++){await start(f);await hook(f,'read');complete(f);}const before=f.calls;f.select('low');const t=await start(f,'Only format the already verified result');assert.equal(f.calls,before+1);assert.equal(t.current,'low');});
test('a new phase after two no-change decisions can actually downshift',async()=>{const f=fixture();const t=await start(f);await hook(f,'read');f.r.observe({method:'item/completed',params:{threadId:'t',item:{type:'agentMessage',text:'Implementation and checks are complete; next only format the verified result.'}}});f.select('low');await hook(f,'checks','All required checks passed');assert.equal(t.current,'low');assert.equal(f.calls,3);assert.equal(f.updates.at(-1).effort,'low');});
test('an observed failure after two no-change decisions is reassessed within the existing ceiling',async()=>{const f=fixture();await start(f);await hook(f,'read');f.select('high');await hook(f,'failed',{exit_code:1,output:'New failure contradicts the previous assumption'});assert.equal(f.calls,3);assert.equal(f.r.turns.get('t').current,'medium');});
test('a transient outage following an unchanged decision still has one bounded recovery',async()=>{const f=fixture();const t=await start(f);f.fail(true);await hook(f,'offline');assert.notEqual(t.retryAt,null);const before=f.calls;await hook(f,'too-soon');assert.equal(f.calls,before);f.advance(15000);f.fail(false);f.select('low');await hook(f,'service-restored');assert.equal(f.calls,before+1);assert.equal(t.current,'low');assert.equal(t.recoveryAttempts,1);});
test('restoring reevaluation keeps the hard call cap and never leaves an expired downgrade',async()=>{const f=fixture();await start(f);await hook(f,'read');f.select('low');await hook(f,'phase');for(let i=0;i<15;i++)await hook(f,'f'+i,{exit_code:1});assert(f.calls<=6);assert.equal(f.r.turns.get('t').current,'medium');});
