// Frozen before paid runs. This oracle is never copied into the task workspace.
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const code={id:'fresh_lru',category:'code',files:{
 'SPEC.md':'Implement simulate(capacity, operations) in cache.mjs. Capacity must be a nonnegative integer or throw RangeError. Operations are put(key,value), get(key), delete(key), represented as objects with op/key/value. Keys are arbitrary strings including __proto__. get returns the stored value and makes the key most recently used; a miss returns null. put replaces or inserts and refreshes recency; evict least recent while over capacity. delete returns whether the key existed. Each put result is null. Return {results,entries}, where entries is [key,value] pairs ordered least to most recently used. Zero capacity retains nothing. Never mutate operations or their values. Unknown op throws TypeError. Undefined stored values are valid and distinct from misses.',
 'cache.mjs':"export function simulate(capacity,operations){const cache={};return {results:operations.map(x=>{if(x.op==='put')cache[x.key]=x.value;return cache[x.key]??null}),entries:Object.entries(cache)};}\n"
},prompt:'Repair cache.mjs to meet SPEC.md. Add meaningful tests and run them, including recency, zero capacity and unusual keys. Do not add dependencies or change SPEC.md.'};
const files={'instructions.md':'Determine the currently approved laboratory calibration protocol. Signed amendments supersede earlier signed rules; proposals never take effect. No actual lab measurements are provided.'};
for(let i=0;i<44;i++)files[`archive/note-${i}.md`]=`Historical calibration note ${i}: previous draft for lab ${i%2?'Quartz':'Opal'}. Old drafts suggested four samples and a temperature of 18 degrees. These historical notes are not the current signed protocol.\n`.repeat(4);
files['policy/signed.md']='Signed protocol: Quartz lab must take 12 samples at 22 degrees Celsius. Discard a batch if deviation is strictly greater than 0.4 in three consecutive readings. Exactly 0.4 is allowed. Reviewer: Anya. This replaces all historical notes.';
files['policy/amendment.md']='Signed amendment for Quartz: require 16 samples and reviewer Boris. Temperature and rejection conditions remain unchanged.';
files['policy/proposal.md']='Unsigned proposal: suggest 6 samples, reviewer Carol, temperature 30 degrees and discard at deviation greater than or equal to 0.4. This is not approved.';
const doc={id:'fresh_protocol',category:'documents',files,prompt:'Resolve the currently approved Quartz calibration protocol. Write findings.data with {samples,temperatureC,deviationLimit,comparison,consecutiveReadings,reviewer,observedOutcome,evidencePaths}. comparison must be greater or greater_or_equal. No measurements means observedOutcome unknown. Write findings.md explaining authority and citing sources. Preserve all original files.'};
export const generalizationTasks=[code,doc];
const oracle=`import assert from 'node:assert/strict';import {simulate as f} from './cache.mjs';
const p=(key,value)=>({op:'put',key,value}),g=key=>({op:'get',key}),d=key=>({op:'delete',key});
const a=[p('__proto__',1),p('b',2),g('__proto__'),p('c',3),g('b'),d('c'),d('c')];a.forEach(Object.freeze);Object.freeze(a);assert.deepEqual(f(2,a),{results:[null,null,1,null,null,true,false],entries:[['__proto__',1]]});assert.deepEqual(f(0,[p('x',7),g('x'),d('x')]),{results:[null,null,false],entries:[]});assert.deepEqual(f(1,[p('x',undefined),g('x'),g('y')]).results,[null,undefined,null]);for(const n of [-1,1.5,Infinity,'2'])assert.throws(()=>f(n,[]),RangeError);assert.throws(()=>f(2,[{op:'unknown'}]),TypeError);
for(let cap=0;cap<5;cap++){const ops=Array.from({length:60},(_,i)=>i%4===0?g('k'+i%7):i%4===1?d('k'+i%7):p('k'+i%7,i));let entries=[],results=[];for(const x of ops){const i=entries.findIndex(y=>y[0]===x.key);if(x.op==='put'){if(i>=0)entries.splice(i,1);entries.push([x.key,x.value]);if(entries.length>cap)entries.shift();results.push(null);}else if(x.op==='get'){if(i<0)results.push(null);else{const v=entries.splice(i,1)[0];entries.push(v);results.push(v[1]);}}else{results.push(i>=0);if(i>=0)entries.splice(i,1);}}assert.deepEqual(f(cap,ops),{entries,results});}console.log('oracle passed');`;
export async function validateGeneralization(task,cwd){const checks=[];const add=(name,pass)=>checks.push({name,pass:Boolean(pass)});
 for(const [p,v]of Object.entries(task.files))if(p!=='cache.mjs')add('protected:'+p,await readFile(cwd+'/'+p,'utf8').then(x=>x===v).catch(()=>false));
 if(task.category==='code'){const r=spawnSync(process.execPath,['--input-type=module','-e',oracle],{cwd,encoding:'utf8',timeout:15000});add('oracle',r.status===0);return{pass:checks.every(x=>x.pass),checks,oracleOutput:(r.stdout+r.stderr).slice(-1800)};}
 let d;try{d=JSON.parse(await readFile(cwd+'/findings.data','utf8'));}catch{}for(const[k,v]of Object.entries({samples:16,temperatureC:22,deviationLimit:.4,comparison:'greater',consecutiveReadings:3,reviewer:'Boris',observedOutcome:'unknown'}))add(k,d?.[k]===v);
 add('evidence',Array.isArray(d?.evidencePaths)&&['policy/signed.md','policy/amendment.md','policy/proposal.md'].every(p=>d.evidencePaths.includes(p))&&d.evidencePaths.every(p=>Object.hasOwn(task.files,p)));add('report',(await readFile(cwd+'/findings.md','utf8').catch(()=>'')).length>80);return{pass:checks.every(x=>x.pass),checks};}
