// Nonrepeating output fixture, distinct from the duplicate-heavy positive control.
import assert from 'node:assert/strict';import{mkdtemp,mkdir,writeFile}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';import{Store,loadKey}from'../../src/core.mjs';import{installHome}from'../../src/setup.mjs';import{createAutomation}from'../../src/automation.mjs';
if(!process.argv.includes('--run'))throw Error('Explicit --run required');
const base=await mkdtemp(join(tmpdir(),'jev-unique-log-')),workspace=join(base,'project');await mkdir(workspace);const store=new Store({home:join(base,'private')}),key=loadKey(installHome()),a=createAutomation({store,key});const session='unique-log-functional';
const lines=Array.from({length:240},(_,i)=>`Museum collection record ${i}: ceramic archive item ${1000+i}, display room ${i%9}, pigment mix ${i%17}, visitor batch ${i}.`);lines[5]='Checkout error: pool limit decreased from 32 to 4 after deployment, causing connection waits.';lines[119]='DNS investigation: every lookup succeeded; the earlier DNS hypothesis is rejected.';lines[230]='Checkout recovery: restore pool limit 32, followed by 200 successful requests with zero timeout.';const text=lines.join('\n');
await a.hook({cwd:workspace,session_id:session,turn_id:'one',hook_event_name:'UserPromptSubmit',prompt:'Diagnose checkout pool regression; retain the DNS counterevidence and recovery observations'});
const result=await a.hook({cwd:workspace,session_id:session,turn_id:'one',hook_event_name:'PostToolUse',tool_use_id:'unique-log-read',tool_name:'exec_command',tool_response:text});
const delivered=result.continue===false?result.stopReason:text;
const events=store.events(store.project(workspace),10000);const outcome=events.find(e=>e.kind==='automatic_output_result');let checks=[];
checks.push({name:'replacement_applied',pass:result.continue===false},{name:'cause_retained',pass:delivered.includes('pool limit decreased')===true},{name:'counterevidence_retained',pass:delivered.includes('every lookup succeeded')===true},{name:'recovery_retained',pass:delivered.includes('200 successful')===true});
const artifact=outcome?.artifactId&&store.get(store.project(workspace),'artifact',outcome.artifactId);checks.push({name:'full_original_recoverable',pass:artifact?.items.map(x=>x.text).join('\n')===text});
const report={at:new Date().toISOString(),kind:'live_jev_unique_log_hook_fixture_not_real_GPT_benchmark',inputLines:240,originalBytes:Buffer.byteLength(text),checks,passed:checks.every(x=>x.pass),outcome,events};await writeFile('docs/reports/validation-20260923/unique-log.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks,outcome}));await a.close();
