const token=location.hash.slice(1); history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id); let dictionary={},current;
async function api(path,data){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});if(!r.ok)throw new Error(dictionary.requestFailed||'Request failed');return r.json();}
async function language(code){dictionary=await fetch('/locales/'+code+'.json').then(r=>r.json());document.documentElement.lang=code;document.querySelectorAll('[data-i]').forEach(e=>e.textContent=dictionary[e.dataset.i]);$('language').value=code;if(current)render(current);}
function render(data){current=data;const {status,metrics,desktop,routing}=data;$('enabled').checked=status.config.enabled;$('memory').checked=status.config.memory;$('calls').textContent=metrics.jev.calls;$('tokens').textContent=(metrics.jev.inputTokens+metrics.jev.outputTokens).toLocaleString();$('cache').textContent=metrics.cacheHits;$('applied').textContent=routing.routing.nativeUpdatesApplied;$('runtime').replaceChildren();const rows={platform:desktop.platform+' / '+desktop.arch,version:desktop.runtimeVersion||'—',installed:desktop.installed,compatible:desktop.compatible,running:desktop.bridgeProcessAlive,keyStatus:status.configured};for(const [key,value]of Object.entries(rows)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=dictionary[key]||key;dd.textContent=typeof value==='boolean'?dictionary[value?'yes':'no']:value;$('runtime').append(dt,dd);}}
async function refresh(){try{render(await api('status'));$('notice').textContent='';}catch(e){$('notice').textContent=e.message;}}
$('language').onchange=async()=>{await language($('language').value);try{await api('config',{locale:$('language').value});}catch(e){$('notice').textContent=e.message;}};
for(const key of ['enabled','memory'])$(key).onchange=async()=>{try{await api('config',{[key]:$(key).checked});await refresh();}catch(e){$('notice').textContent=e.message;}};
$('credentials').onsubmit=async e=>{e.preventDefault();try{await api('key',{key:$('key').value});$('key').value='';await refresh();$('notice').textContent=dictionary.saved;}catch(error){$('notice').textContent=error.message;}};
$('refresh').onclick=refresh;
(async()=>{await language('en');await refresh();if(current)await language(current.status.config.locale);})();
